export const ADD_TASK = 'TASKS:ADD_TASK';

export const RECEIVE_TASK = 'TASKS:RECEIVE_TASK';

export const DELETE_TASK = 'TASKS:DELETE_TASK';

export const LOADING_TASKS = 'TASKS:LOADING_TASKS';

export const LOADING_TASKS_SUCCESS = 'TASKS:LOADING_TASKS_SUCCESS';

export const LOADING_TASKS_FAILED = 'TASKS:LOADING_TASKS_FAILED';