export const ADD_TASK = 'TASKS:ADD_TASK';

export const RECEIVE_TASK = 'TASKS:RECEIVE_TASK';

export const UPDATE_TASK = 'TASKS:UPDATE_TASK';

export const REPLACE_TASKS = 'TASKS:REPLACE_TASKS';

export const DELETE_TASK = 'TASKS:DELETE_TASK';

export const SUBSCRIBE_TO_TASKS = 'TASKS:SUBSCRIBE_TO_TASKS';

export const UNSUBSCRIBE_TO_TASKS = 'TASKS:UNSUBSCRIBE_TO_TASKS';

export const LOADING_TASKS = 'TASKS:LOADING_TASKS';

export const LOADING_TASKS_SUCCESS = 'TASKS:LOADING_TASKS_SUCCESS';

export const LOADING_TASKS_FAILED = 'TASKS:LOADING_TASKS_FAILED';